--Explore All Objects in Database
SELECT * FROM INFORMATION_SCHEMA.TABLES

--Explore AllColumns in the Database
SELECT *FROM INFORMATION_SCHEMA.COLUMNS

--Dimension Exploration
--1.gold.dim_customers
--Exploring Countries Customers are from
SELECT
DISTINCT country
FROM gold.dim_customers

--2.gold.dim_products
--Exploring all the categories in the product
SELECT DISTINCT category, subcategory, product_name FROM gold.dim_products

--Date Exploration
--Identify the earliest and latest dates, understand the scope of data and the timespan.
--Find the Date of the First and the Last orders
--Find how many years of sales are available
SELECT
MIN(order_date) AS First_Order,
MAX(order_date) AS Last_Order,
DATEDIFF(MONTH, MIN(order_date),MAX(order_date)) AS order_range_month
FROM gold.fact_sales

--Find youngest and the oldest customer
SELECT
MIN(birthdate) AS youngest_customer,
DATEDIFF(YEAR,MIN(birthdate),GETDATE()) AS oldest_customer_age,
MAX(birthdate) AS oldest_customer,
DATEDIFF(YEAR,MAX(birthdate),GETDATE()) AS youngest_customer_age
FROM gold.dim_customers

--Measures Exploration
--Calculate the Metric of the Business
--Highest Level of Aggregation | Lowest Level of Details-
--1. Find the Total Sales
SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales;

--2.Find how many items are sold
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales;

--3.Find the Average Selling Price
SELECT AVG(price) AS average_selling_price FROM gold.fact_sales;

--4.Find the Total Number of Orders
SELECT COUNT(DISTINCT order_number) AS total_number_of_orders FROM gold.fact_sales;

--5.Find the Total Number of Products
SELECT COUNT(DISTINCT product_name)  AS total_number_products FROM gold.dim_products;

--6.Find the Total Number of Customers
SELECT COUNT (customer_id) AS total_customer FROM gold.dim_customers;

--7.Find the Total Number of Customers that has Placed an Order
SELECT COUNT(DISTINCT customer_key) AS total_cust_placed_order FROM gold.fact_sales;

--Generate a Report that shows all key metrics of the business

SELECT 'Total Sales'AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity)  FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total no. of Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total no. of Products', COUNT(DISTINCT product_name) FROM gold.dim_products
UNION
SELECT 'Total Customers',COUNT(customer_id) FROM gold.dim_customers
UNION ALL
SELECT 'Customer who placed an order', COUNT(DISTINCT customer_key) FROM gold.fact_sales

--Magnitude Analysis: Compare the measure values by categories. It helps us understand the importance of different categories.
--1.Find total customers by country
SELECT
country,
COUNT(customer_id) AS total_customer
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customer DESC

--2.Find total customers by gender
SELECT
gender,
COUNT(customer_id) AS total_customer
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customer DESC

--3.Find total product by category
SELECT
category,
COUNT(product_id) AS no_of_product
FROM gold.dim_products
GROUP BY category
ORDER BY no_of_product DESC

--total product by sub category
SELECT 
subcategory,
COUNT(product_id) AS no_of_product
FROM gold.dim_products
GROUP BY subcategory
ORDER BY no_of_product DESC

--4.What is the average cost in each category?
SELECT
category,
AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

--5.What is the total revenue generated for each category?
SELECT
p.category,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key=f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

--6.Find total revenue generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key=f.customer_key
GROUP BY c.customer_key,
         c.first_name,
         c.last_name
ORDER BY total_revenue DESC

--7.What is the distribution of sold item across each country?
SELECT
c.country,
SUM(f.quantity) AS item_sold
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key=f.customer_key
GROUP BY c.country
ORDER BY item_sold DESC



--Ranking Analysis

--Which 5 products generate the highest revenue
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS revenue
FROM gold.dim_products p
LEFT JOIN gold.fact_sales f
ON p.product_key=f.product_key
GROUP BY p.product_name
ORDER BY revenue DESC

--What are the 5 worst-performing products in terms of sales
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS revenue
FROM gold.dim_products p
LEFT JOIN gold.fact_sales f
ON p.product_key=f.product_key
GROUP BY p.product_name
HAVING SUM(f.sales_amount) IS NOT NULL
ORDER BY revenue ASC

--Top 10 customer who have generated the highest revenue
SELECT TOP 10
    c.customer_id,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_customers c
    ON c.customer_id=f.customer_key
    GROUP BY customer_id,
             c.first_name,
             c.last_name
    HAVING SUM(f.sales_amount) IS NOT NULL
    ORDER BY total_revenue DESC

--Top 3 customers with the fewest orders
SELECT TOP 3
    c.customer_id,
    c.first_name,
    c.last_name,
    COUNT(f.order_number) AS no_of_orders
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_customers c
    ON c.customer_id=f.customer_key
    GROUP BY customer_id,
             c.first_name,
             c.last_name
    HAVING SUM(f.sales_amount) IS NOT NULL
    ORDER BY no_of_orders ASC
